# Generated by Django 5.1.1 on 2024-10-11 18:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizassignment',
            name='generated_content',
        ),
        migrations.RemoveField(
            model_name='student',
            name='weakness',
        ),
        migrations.AddField(
            model_name='quizassignment',
            name='is_support_content_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quizassignment',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255)),
                ('option_1', models.CharField(max_length=255)),
                ('option_2', models.CharField(max_length=255)),
                ('option_3', models.CharField(max_length=255)),
                ('option_4', models.CharField(max_length=255)),
                ('correct_answer', models.IntegerField()),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='classroom.quizassignment')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('marks', models.DecimalField(decimal_places=2, default=-1, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quiz_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.quizassignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='classroom.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.IntegerField()),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.question')),
                ('student_assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.studentassessment')),
            ],
        ),
        migrations.DeleteModel(
            name='StudentMarks',
        ),
    ]
