# Generated by Django 5.1.1 on 2024-10-29 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_alter_student_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizassignment',
            name='uuid',
        ),
    ]
